// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_check (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in1_dout,
        in1_empty_n,
        in1_read,
        in2_dout,
        in2_empty_n,
        in2_read,
        out_V_din,
        out_V_full_n,
        out_V_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state5 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [1:0] in1_dout;
input   in1_empty_n;
output   in1_read;
input  [1:0] in2_dout;
input   in2_empty_n;
output   in2_read;
output  [0:0] out_V_din;
input   out_V_full_n;
output   out_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in1_read;
reg in2_read;
reg out_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in1_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln24_reg_89;
reg    in2_blk_n;
reg    out_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln24_reg_89_pp0_iter1_reg;
reg   [10:0] i_reg_55;
wire   [10:0] i_4_fu_66_p2;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln24_fu_72_p2;
wire   [0:0] icmp_ln870_fu_78_p2;
reg   [0:0] icmp_ln870_reg_93;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_block_pp0_stage0_01001;
wire    ap_CS_fsm_state5;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln24_fu_72_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_55 <= i_4_fu_66_p2;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_55 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln24_reg_89 <= icmp_ln24_fu_72_p2;
        icmp_ln24_reg_89_pp0_iter1_reg <= icmp_ln24_reg_89;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln24_reg_89 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln870_reg_93 <= icmp_ln870_fu_78_p2;
    end
end

always @ (*) begin
    if ((icmp_ln24_fu_72_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln24_reg_89 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in1_blk_n = in1_empty_n;
    end else begin
        in1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln24_reg_89 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in1_read = 1'b1;
    end else begin
        in1_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln24_reg_89 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in2_blk_n = in2_empty_n;
    end else begin
        in2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln24_reg_89 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in2_read = 1'b1;
    end else begin
        in2_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln24_reg_89_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        out_V_blk_n = out_V_full_n;
    end else begin
        out_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln24_reg_89_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        out_V_write = 1'b1;
    end else begin
        out_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln24_fu_72_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)) & ~((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)) | ((icmp_ln24_fu_72_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((icmp_ln24_reg_89_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (out_V_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln24_reg_89 == 1'd0) & (in2_empty_n == 1'b0)) | ((icmp_ln24_reg_89 == 1'd0) & (in1_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((icmp_ln24_reg_89_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (out_V_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln24_reg_89 == 1'd0) & (in2_empty_n == 1'b0)) | ((icmp_ln24_reg_89 == 1'd0) & (in1_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((icmp_ln24_reg_89_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (out_V_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln24_reg_89 == 1'd0) & (in2_empty_n == 1'b0)) | ((icmp_ln24_reg_89 == 1'd0) & (in1_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((icmp_ln24_reg_89 == 1'd0) & (in2_empty_n == 1'b0)) | ((icmp_ln24_reg_89 == 1'd0) & (in1_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = ((icmp_ln24_reg_89_pp0_iter1_reg == 1'd0) & (out_V_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign i_4_fu_66_p2 = (i_reg_55 + 11'd1);

assign icmp_ln24_fu_72_p2 = ((i_reg_55 == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln870_fu_78_p2 = ((in1_dout == in2_dout) ? 1'b1 : 1'b0);

assign out_V_din = icmp_ln870_reg_93;

endmodule //top_check
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps

module top_fifo_w2_d2_S_shiftReg (
    clk,
    data,
    ce,
    a,
    q);

parameter DATA_WIDTH = 32'd2;
parameter ADDR_WIDTH = 32'd1;
parameter DEPTH = 2'd2;

input clk;
input [DATA_WIDTH-1:0] data;
input ce;
input [ADDR_WIDTH-1:0] a;
output [DATA_WIDTH-1:0] q;

reg[DATA_WIDTH-1:0] SRL_SIG [0:DEPTH-1];
integer i;

always @ (posedge clk)
    begin
        if (ce)
        begin
            for (i=0;i<DEPTH-1;i=i+1)
                SRL_SIG[i+1] <= SRL_SIG[i];
            SRL_SIG[0] <= data;
        end
    end

assign q = SRL_SIG[a];

endmodule

module top_fifo_w2_d2_S (
    clk,
    reset,
    if_empty_n,
    if_read_ce,
    if_read,
    if_dout,
    if_full_n,
    if_write_ce,
    if_write,
    if_din);

parameter MEM_STYLE   = "shiftreg";
parameter DATA_WIDTH  = 32'd2;
parameter ADDR_WIDTH  = 32'd1;
parameter DEPTH       = 2'd2;

input clk;
input reset;
output if_empty_n;
input if_read_ce;
input if_read;
output[DATA_WIDTH - 1:0] if_dout;
output if_full_n;
input if_write_ce;
input if_write;
input[DATA_WIDTH - 1:0] if_din;

wire[ADDR_WIDTH - 1:0] shiftReg_addr ;
wire[DATA_WIDTH - 1:0] shiftReg_data, shiftReg_q;
wire                     shiftReg_ce;
reg[ADDR_WIDTH:0] mOutPtr = ~{(ADDR_WIDTH+1){1'b0}};
reg internal_empty_n = 0;
reg internal_full_n = 1;

assign if_full_n = internal_full_n;
assign if_empty_n = internal_empty_n;
assign shiftReg_data = if_din;
assign if_dout = shiftReg_q;

always @ (posedge clk) begin
    if (reset == 1'b1)
    begin
        mOutPtr <= ~{ADDR_WIDTH+1{1'b0}};
        internal_empty_n <= 1'b0;
        internal_full_n <= 1'b1;
    end
    else begin
        if (((if_read & if_read_ce) == 1 & internal_empty_n == 1) && 
            ((if_write & if_write_ce) == 0 | internal_full_n == 0))
        begin
            mOutPtr <= mOutPtr - 2'd1;
            if (mOutPtr == 2'd0)
                internal_empty_n <= 1'b0;
            internal_full_n <= 1'b1;
        end 
        else if (((if_read & if_read_ce) == 0 | internal_empty_n == 0) && 
            ((if_write & if_write_ce) == 1 & internal_full_n == 1))
        begin
            mOutPtr <= mOutPtr + 2'd1;
            internal_empty_n <= 1'b1;
            if (mOutPtr == DEPTH - 2'd2)
                internal_full_n <= 1'b0;
        end 
    end
end

assign shiftReg_addr = mOutPtr[ADDR_WIDTH] == 1'b0 ? mOutPtr[ADDR_WIDTH-1:0]:{ADDR_WIDTH{1'b0}};
assign shiftReg_ce = (if_write & if_write_ce) & internal_full_n;

top_fifo_w2_d2_S_shiftReg 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH),
    .DEPTH(DEPTH))
U_top_fifo_w2_d2_S_ram (
    .clk(clk),
    .data(shiftReg_data),
    .ce(shiftReg_ce),
    .a(shiftReg_addr),
    .q(shiftReg_q));

endmodule  

// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_mac_impl_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_1_dout,
        in_1_empty_n,
        in_1_read,
        in_2_dout,
        in_2_empty_n,
        in_2_read,
        out_r_din,
        out_r_full_n,
        out_r_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state5 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [1:0] in_1_dout;
input   in_1_empty_n;
output   in_1_read;
input  [1:0] in_2_dout;
input   in_2_empty_n;
output   in_2_read;
output  [1:0] out_r_din;
input   out_r_full_n;
output   out_r_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_1_read;
reg in_2_read;
reg out_r_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in_1_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln35_reg_186;
reg    in_2_blk_n;
reg    out_r_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln38_1_reg_210;
reg   [12:0] indvar_flatten_reg_79;
reg   [2:0] j_reg_90;
reg   [1:0] sum_val_V_reg_101;
wire   [12:0] add_ln35_fu_113_p2;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln35_fu_119_p2;
reg   [0:0] icmp_ln35_reg_186_pp0_iter1_reg;
wire   [0:0] icmp_ln38_fu_125_p2;
reg   [0:0] icmp_ln38_reg_190;
reg  signed [1:0] a_V_reg_195;
reg  signed [1:0] b_V_reg_200;
wire   [2:0] j_2_fu_137_p3;
reg   [2:0] j_2_reg_205;
wire   [0:0] icmp_ln38_1_fu_145_p2;
wire   [1:0] sum_val_V_2_fu_174_p2;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
reg    ap_condition_pp0_exit_iter1_state3;
reg   [2:0] ap_phi_mux_j_phi_fu_94_p4;
reg    ap_block_pp0_stage0_01001;
wire   [2:0] add_ln38_fu_131_p2;
wire   [3:0] mul_ln1345_fu_164_p2;
wire   [1:0] m_fu_170_p1;
wire   [1:0] select_ln35_fu_151_p3;
wire    ap_CS_fsm_state5;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

top_mul_2s_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2s_2s_4_1_1_U7(
    .din0(b_V_reg_200),
    .din1(a_V_reg_195),
    .dout(mul_ln1345_fu_164_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((((ap_enable_reg_pp0_iter0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter1_state3)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter1_state3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln35_fu_119_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_reg_79 <= add_ln35_fu_113_p2;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_79 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln35_reg_186_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        j_reg_90 <= j_2_reg_205;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        j_reg_90 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln35_reg_186_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sum_val_V_reg_101 <= sum_val_V_2_fu_174_p2;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sum_val_V_reg_101 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln35_reg_186 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_V_reg_195 <= in_1_dout;
        b_V_reg_200 <= in_2_dout;
        icmp_ln38_1_reg_210 <= icmp_ln38_1_fu_145_p2;
        icmp_ln38_reg_190 <= icmp_ln38_fu_125_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln35_reg_186 <= icmp_ln35_fu_119_p2;
        icmp_ln35_reg_186_pp0_iter1_reg <= icmp_ln35_reg_186;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln35_reg_186 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_2_reg_205 <= j_2_fu_137_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_condition_pp0_exit_iter1_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter1_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln35_fu_119_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln35_reg_186_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_j_phi_fu_94_p4 = j_2_reg_205;
    end else begin
        ap_phi_mux_j_phi_fu_94_p4 = j_reg_90;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln35_reg_186 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_1_blk_n = in_1_empty_n;
    end else begin
        in_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln35_reg_186 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_1_read = 1'b1;
    end else begin
        in_1_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln35_reg_186 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_2_blk_n = in_2_empty_n;
    end else begin
        in_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln35_reg_186 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_2_read = 1'b1;
    end else begin
        in_2_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln38_1_reg_210 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        out_r_blk_n = out_r_full_n;
    end else begin
        out_r_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln38_1_reg_210 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        out_r_write = 1'b1;
    end else begin
        out_r_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln35_fu_113_p2 = (indvar_flatten_reg_79 + 13'd1);

assign add_ln38_fu_131_p2 = (ap_phi_mux_j_phi_fu_94_p4 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((icmp_ln38_1_reg_210 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (out_r_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln35_reg_186 == 1'd0) & (in_2_empty_n == 1'b0)) | ((icmp_ln35_reg_186 == 1'd0) & (in_1_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((icmp_ln38_1_reg_210 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (out_r_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln35_reg_186 == 1'd0) & (in_2_empty_n == 1'b0)) | ((icmp_ln35_reg_186 == 1'd0) & (in_1_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((icmp_ln38_1_reg_210 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (out_r_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln35_reg_186 == 1'd0) & (in_2_empty_n == 1'b0)) | ((icmp_ln35_reg_186 == 1'd0) & (in_1_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((icmp_ln35_reg_186 == 1'd0) & (in_2_empty_n == 1'b0)) | ((icmp_ln35_reg_186 == 1'd0) & (in_1_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = ((icmp_ln38_1_reg_210 == 1'd1) & (out_r_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign icmp_ln35_fu_119_p2 = ((indvar_flatten_reg_79 == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln38_1_fu_145_p2 = ((j_2_fu_137_p3 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_125_p2 = ((ap_phi_mux_j_phi_fu_94_p4 == 3'd4) ? 1'b1 : 1'b0);

assign j_2_fu_137_p3 = ((icmp_ln38_fu_125_p2[0:0] == 1'b1) ? 3'd1 : add_ln38_fu_131_p2);

assign m_fu_170_p1 = mul_ln1345_fu_164_p2[1:0];

assign out_r_din = (m_fu_170_p1 + select_ln35_fu_151_p3);

assign select_ln35_fu_151_p3 = ((icmp_ln38_reg_190[0:0] == 1'b1) ? 2'd0 : sum_val_V_reg_101);

assign sum_val_V_2_fu_174_p2 = (m_fu_170_p1 + select_ln35_fu_151_p3);

endmodule //top_mac_impl_1
// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_mac_impl_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_1_dout,
        in_1_empty_n,
        in_1_read,
        in_2_dout,
        in_2_empty_n,
        in_2_read,
        out_r_din,
        out_r_full_n,
        out_r_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [1:0] in_1_dout;
input   in_1_empty_n;
output   in_1_read;
input  [1:0] in_2_dout;
input   in_2_empty_n;
output   in_2_read;
output  [1:0] out_r_din;
input   out_r_full_n;
output   out_r_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_1_read;
reg in_2_read;
reg out_r_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in_1_blk_n;
wire    ap_CS_fsm_state4;
reg   [0:0] icmp_ln58_reg_170;
reg    in_2_blk_n;
reg    out_r_blk_n;
wire   [10:0] i_3_fu_109_p2;
reg   [10:0] i_3_reg_157;
wire    ap_CS_fsm_state2;
wire   [2:0] j_1_fu_121_p2;
reg   [2:0] j_1_reg_165;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln58_fu_127_p2;
wire   [1:0] sum_val_V_1_fu_151_p2;
reg    ap_block_state4;
reg   [10:0] i_reg_75;
reg    ap_block_state1;
reg   [2:0] j_reg_86;
wire   [0:0] icmp_ln54_fu_115_p2;
reg   [1:0] sum_val_V_reg_97;
wire   [3:0] mul_ln1345_fu_141_p2;
wire   [1:0] m_fu_147_p1;
reg   [3:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
end

top_mul_2s_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2s_2s_4_1_1_U12(
    .din0(in_2_dout),
    .din1(in_1_dout),
    .dout(mul_ln1345_fu_141_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln54_fu_115_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~(((icmp_ln58_reg_170 == 1'd1) & (out_r_full_n == 1'b0)) | ((icmp_ln58_reg_170 == 1'd0) & (in_2_empty_n == 1'b0)) | ((icmp_ln58_reg_170 == 1'd0) & (in_1_empty_n == 1'b0))) & (icmp_ln58_reg_170 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        i_reg_75 <= i_3_reg_157;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_75 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((icmp_ln58_reg_170 == 1'd1) & (out_r_full_n == 1'b0)) | ((icmp_ln58_reg_170 == 1'd0) & (in_2_empty_n == 1'b0)) | ((icmp_ln58_reg_170 == 1'd0) & (in_1_empty_n == 1'b0))) & (icmp_ln58_reg_170 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        j_reg_86 <= j_1_reg_165;
    end else if (((icmp_ln54_fu_115_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_reg_86 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((icmp_ln58_reg_170 == 1'd1) & (out_r_full_n == 1'b0)) | ((icmp_ln58_reg_170 == 1'd0) & (in_2_empty_n == 1'b0)) | ((icmp_ln58_reg_170 == 1'd0) & (in_1_empty_n == 1'b0))) & (icmp_ln58_reg_170 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        sum_val_V_reg_97 <= sum_val_V_1_fu_151_p2;
    end else if (((icmp_ln54_fu_115_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        sum_val_V_reg_97 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_3_reg_157 <= i_3_fu_109_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        icmp_ln58_reg_170 <= icmp_ln58_fu_127_p2;
        j_1_reg_165 <= j_1_fu_121_p2;
    end
end

always @ (*) begin
    if (((icmp_ln54_fu_115_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln54_fu_115_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln58_reg_170 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        in_1_blk_n = in_1_empty_n;
    end else begin
        in_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((icmp_ln58_reg_170 == 1'd1) & (out_r_full_n == 1'b0)) | ((icmp_ln58_reg_170 == 1'd0) & (in_2_empty_n == 1'b0)) | ((icmp_ln58_reg_170 == 1'd0) & (in_1_empty_n == 1'b0))) & (icmp_ln58_reg_170 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        in_1_read = 1'b1;
    end else begin
        in_1_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln58_reg_170 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        in_2_blk_n = in_2_empty_n;
    end else begin
        in_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((icmp_ln58_reg_170 == 1'd1) & (out_r_full_n == 1'b0)) | ((icmp_ln58_reg_170 == 1'd0) & (in_2_empty_n == 1'b0)) | ((icmp_ln58_reg_170 == 1'd0) & (in_1_empty_n == 1'b0))) & (icmp_ln58_reg_170 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        in_2_read = 1'b1;
    end else begin
        in_2_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln58_reg_170 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_r_blk_n = out_r_full_n;
    end else begin
        out_r_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((icmp_ln58_reg_170 == 1'd1) & (out_r_full_n == 1'b0)) | ((icmp_ln58_reg_170 == 1'd0) & (in_2_empty_n == 1'b0)) | ((icmp_ln58_reg_170 == 1'd0) & (in_1_empty_n == 1'b0))) & (icmp_ln58_reg_170 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_r_write = 1'b1;
    end else begin
        out_r_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln54_fu_115_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if ((~(((icmp_ln58_reg_170 == 1'd1) & (out_r_full_n == 1'b0)) | ((icmp_ln58_reg_170 == 1'd0) & (in_2_empty_n == 1'b0)) | ((icmp_ln58_reg_170 == 1'd0) & (in_1_empty_n == 1'b0))) & (icmp_ln58_reg_170 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if ((~(((icmp_ln58_reg_170 == 1'd1) & (out_r_full_n == 1'b0)) | ((icmp_ln58_reg_170 == 1'd0) & (in_2_empty_n == 1'b0)) | ((icmp_ln58_reg_170 == 1'd0) & (in_1_empty_n == 1'b0))) & (icmp_ln58_reg_170 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state4 = (((icmp_ln58_reg_170 == 1'd1) & (out_r_full_n == 1'b0)) | ((icmp_ln58_reg_170 == 1'd0) & (in_2_empty_n == 1'b0)) | ((icmp_ln58_reg_170 == 1'd0) & (in_1_empty_n == 1'b0)));
end

assign i_3_fu_109_p2 = (i_reg_75 + 11'd1);

assign icmp_ln54_fu_115_p2 = ((i_reg_75 == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln58_fu_127_p2 = ((j_reg_86 == 3'd4) ? 1'b1 : 1'b0);

assign j_1_fu_121_p2 = (j_reg_86 + 3'd1);

assign m_fu_147_p1 = mul_ln1345_fu_141_p2[1:0];

assign out_r_din = sum_val_V_reg_97;

assign sum_val_V_1_fu_151_p2 = (m_fu_147_p1 + sum_val_V_reg_97);

endmodule //top_mac_impl_2
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps

(* use_dsp = "no" *) module top_mul_2s_2s_4_1_1_Mul_LUT_0(a, b, p);
input[2 - 1 : 0] a; 
input[2 - 1 : 0] b; 
output[4 - 1 : 0] p;

assign p = $signed(a) * $signed(b);
endmodule
`timescale 1 ns / 1 ps
module top_mul_2s_2s_4_1_1(
    din0,
    din1,
    dout);

parameter ID = 32'd1;
parameter NUM_STAGE = 32'd1;
parameter din0_WIDTH = 32'd1;
parameter din1_WIDTH = 32'd1;
parameter dout_WIDTH = 32'd1;
input[din0_WIDTH - 1:0] din0;
input[din1_WIDTH - 1:0] din1;
output[dout_WIDTH - 1:0] dout;



top_mul_2s_2s_4_1_1_Mul_LUT_0 top_mul_2s_2s_4_1_1_Mul_LUT_0_U(
    .a( din0 ),
    .b( din1 ),
    .p( dout ));

endmodule

// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_sp3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        mem1_V_dout,
        mem1_V_empty_n,
        mem1_V_read,
        out1_din,
        out1_full_n,
        out1_write,
        out2_din,
        out2_full_n,
        out2_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [1:0] mem1_V_dout;
input   mem1_V_empty_n;
output   mem1_V_read;
output  [1:0] out1_din;
input   out1_full_n;
output   out1_write;
output  [1:0] out2_din;
input   out2_full_n;
output   out2_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg mem1_V_read;
reg out1_write;
reg out2_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    mem1_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln13_reg_86;
reg    out1_blk_n;
reg    out2_blk_n;
reg   [12:0] i_reg_58;
wire   [12:0] i_1_fu_69_p2;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln13_fu_75_p2;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_block_pp0_stage0_01001;
wire    ap_CS_fsm_state4;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln13_fu_75_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_58 <= i_1_fu_69_p2;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_58 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln13_reg_86 <= icmp_ln13_fu_75_p2;
    end
end

always @ (*) begin
    if ((icmp_ln13_fu_75_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_86 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mem1_V_blk_n = mem1_V_empty_n;
    end else begin
        mem1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_86 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mem1_V_read = 1'b1;
    end else begin
        mem1_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_86 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out1_blk_n = out1_full_n;
    end else begin
        out1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_86 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out1_write = 1'b1;
    end else begin
        out1_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_86 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out2_blk_n = out2_full_n;
    end else begin
        out2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_86 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out2_write = 1'b1;
    end else begin
        out2_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((icmp_ln13_fu_75_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((icmp_ln13_fu_75_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln13_reg_86 == 1'd0) & (out2_full_n == 1'b0)) | ((icmp_ln13_reg_86 == 1'd0) & (out1_full_n == 1'b0)) | ((icmp_ln13_reg_86 == 1'd0) & (mem1_V_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln13_reg_86 == 1'd0) & (out2_full_n == 1'b0)) | ((icmp_ln13_reg_86 == 1'd0) & (out1_full_n == 1'b0)) | ((icmp_ln13_reg_86 == 1'd0) & (mem1_V_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln13_reg_86 == 1'd0) & (out2_full_n == 1'b0)) | ((icmp_ln13_reg_86 == 1'd0) & (out1_full_n == 1'b0)) | ((icmp_ln13_reg_86 == 1'd0) & (mem1_V_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((icmp_ln13_reg_86 == 1'd0) & (out2_full_n == 1'b0)) | ((icmp_ln13_reg_86 == 1'd0) & (out1_full_n == 1'b0)) | ((icmp_ln13_reg_86 == 1'd0) & (mem1_V_empty_n == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign i_1_fu_69_p2 = (i_reg_58 + 13'd1);

assign icmp_ln13_fu_75_p2 = ((i_reg_58 == 13'd4096) ? 1'b1 : 1'b0);

assign out1_din = mem1_V_dout;

assign out2_din = mem1_V_dout;

endmodule //top_sp3
// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_sp (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        mem1_V_dout,
        mem1_V_empty_n,
        mem1_V_read,
        out1_din,
        out1_full_n,
        out1_write,
        out2_din,
        out2_full_n,
        out2_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [1:0] mem1_V_dout;
input   mem1_V_empty_n;
output   mem1_V_read;
output  [1:0] out1_din;
input   out1_full_n;
output   out1_write;
output  [1:0] out2_din;
input   out2_full_n;
output   out2_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg mem1_V_read;
reg out1_write;
reg out2_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    mem1_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln13_reg_86;
reg    out1_blk_n;
reg    out2_blk_n;
reg   [12:0] i_reg_58;
wire   [12:0] i_2_fu_69_p2;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln13_fu_75_p2;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_block_pp0_stage0_01001;
wire    ap_CS_fsm_state4;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln13_fu_75_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_58 <= i_2_fu_69_p2;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_58 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln13_reg_86 <= icmp_ln13_fu_75_p2;
    end
end

always @ (*) begin
    if ((icmp_ln13_fu_75_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_86 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mem1_V_blk_n = mem1_V_empty_n;
    end else begin
        mem1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_86 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mem1_V_read = 1'b1;
    end else begin
        mem1_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_86 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out1_blk_n = out1_full_n;
    end else begin
        out1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_86 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out1_write = 1'b1;
    end else begin
        out1_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_86 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out2_blk_n = out2_full_n;
    end else begin
        out2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_86 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out2_write = 1'b1;
    end else begin
        out2_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((icmp_ln13_fu_75_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((icmp_ln13_fu_75_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln13_reg_86 == 1'd0) & (out2_full_n == 1'b0)) | ((icmp_ln13_reg_86 == 1'd0) & (out1_full_n == 1'b0)) | ((icmp_ln13_reg_86 == 1'd0) & (mem1_V_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln13_reg_86 == 1'd0) & (out2_full_n == 1'b0)) | ((icmp_ln13_reg_86 == 1'd0) & (out1_full_n == 1'b0)) | ((icmp_ln13_reg_86 == 1'd0) & (mem1_V_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln13_reg_86 == 1'd0) & (out2_full_n == 1'b0)) | ((icmp_ln13_reg_86 == 1'd0) & (out1_full_n == 1'b0)) | ((icmp_ln13_reg_86 == 1'd0) & (mem1_V_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((icmp_ln13_reg_86 == 1'd0) & (out2_full_n == 1'b0)) | ((icmp_ln13_reg_86 == 1'd0) & (out1_full_n == 1'b0)) | ((icmp_ln13_reg_86 == 1'd0) & (mem1_V_empty_n == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign i_2_fu_69_p2 = (i_reg_58 + 13'd1);

assign icmp_ln13_fu_75_p2 = ((i_reg_58 == 13'd4096) ? 1'b1 : 1'b0);

assign out1_din = mem1_V_dout;

assign out2_din = mem1_V_dout;

endmodule //top_sp
// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="top_top,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.295000,HLS_SYN_LAT=11265,HLS_SYN_TPT=11266,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=732,HLS_SYN_LUT=1148,HLS_VERSION=2020_2}" *)

module top (
        mem1_V_dout,
        mem1_V_empty_n,
        mem1_V_read,
        mem2_V_dout,
        mem2_V_empty_n,
        mem2_V_read,
        out_V_din,
        out_V_full_n,
        out_V_write,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);


input  [1:0] mem1_V_dout;
input   mem1_V_empty_n;
output   mem1_V_read;
input  [1:0] mem2_V_dout;
input   mem2_V_empty_n;
output   mem2_V_read;
output  [0:0] out_V_din;
input   out_V_full_n;
output   out_V_write;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire    sp3_U0_ap_start;
wire    sp3_U0_ap_done;
wire    sp3_U0_ap_continue;
wire    sp3_U0_ap_idle;
wire    sp3_U0_ap_ready;
wire    sp3_U0_mem1_V_read;
wire   [1:0] sp3_U0_out1_din;
wire    sp3_U0_out1_write;
wire   [1:0] sp3_U0_out2_din;
wire    sp3_U0_out2_write;
wire    sp_U0_ap_start;
wire    sp_U0_ap_done;
wire    sp_U0_ap_continue;
wire    sp_U0_ap_idle;
wire    sp_U0_ap_ready;
wire    sp_U0_mem1_V_read;
wire   [1:0] sp_U0_out1_din;
wire    sp_U0_out1_write;
wire   [1:0] sp_U0_out2_din;
wire    sp_U0_out2_write;
wire    mac_impl_1_U0_ap_start;
wire    mac_impl_1_U0_ap_done;
wire    mac_impl_1_U0_ap_continue;
wire    mac_impl_1_U0_ap_idle;
wire    mac_impl_1_U0_ap_ready;
wire    mac_impl_1_U0_in_1_read;
wire    mac_impl_1_U0_in_2_read;
wire   [1:0] mac_impl_1_U0_out_r_din;
wire    mac_impl_1_U0_out_r_write;
reg    ap_sync_reg_mac_impl_1_U0_ap_start;
wire    mac_impl_2_U0_ap_start;
wire    mac_impl_2_U0_ap_done;
wire    mac_impl_2_U0_ap_continue;
wire    mac_impl_2_U0_ap_idle;
wire    mac_impl_2_U0_ap_ready;
wire    mac_impl_2_U0_in_1_read;
wire    mac_impl_2_U0_in_2_read;
wire   [1:0] mac_impl_2_U0_out_r_din;
wire    mac_impl_2_U0_out_r_write;
reg    ap_sync_reg_mac_impl_2_U0_ap_start;
wire    check_U0_ap_start;
wire    check_U0_ap_done;
wire    check_U0_ap_continue;
wire    check_U0_ap_idle;
wire    check_U0_ap_ready;
wire    check_U0_in1_read;
wire    check_U0_in2_read;
wire   [0:0] check_U0_out_V_din;
wire    check_U0_out_V_write;
reg    ap_sync_reg_check_U0_ap_start;
wire    ap_sync_continue;
wire    f1_full_n;
wire   [1:0] f1_dout;
wire    f1_empty_n;
wire    f2_full_n;
wire   [1:0] f2_dout;
wire    f2_empty_n;
wire    f3_full_n;
wire   [1:0] f3_dout;
wire    f3_empty_n;
wire    f4_full_n;
wire   [1:0] f4_dout;
wire    f4_empty_n;
wire    f5_full_n;
wire   [1:0] f5_dout;
wire    f5_empty_n;
wire    f6_full_n;
wire   [1:0] f6_dout;
wire    f6_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_sp3_U0_ap_ready;
wire    ap_sync_sp3_U0_ap_ready;
reg    ap_sync_reg_sp_U0_ap_ready;
wire    ap_sync_sp_U0_ap_ready;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_mac_impl_1_U0_ap_start = 1'b0;
#0 ap_sync_reg_mac_impl_2_U0_ap_start = 1'b0;
#0 ap_sync_reg_check_U0_ap_start = 1'b0;
#0 ap_sync_reg_sp3_U0_ap_ready = 1'b0;
#0 ap_sync_reg_sp_U0_ap_ready = 1'b0;
end

top_sp3 sp3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(sp3_U0_ap_start),
    .ap_done(sp3_U0_ap_done),
    .ap_continue(sp3_U0_ap_continue),
    .ap_idle(sp3_U0_ap_idle),
    .ap_ready(sp3_U0_ap_ready),
    .mem1_V_dout(mem1_V_dout),
    .mem1_V_empty_n(mem1_V_empty_n),
    .mem1_V_read(sp3_U0_mem1_V_read),
    .out1_din(sp3_U0_out1_din),
    .out1_full_n(f1_full_n),
    .out1_write(sp3_U0_out1_write),
    .out2_din(sp3_U0_out2_din),
    .out2_full_n(f2_full_n),
    .out2_write(sp3_U0_out2_write)
);

top_sp sp_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(sp_U0_ap_start),
    .ap_done(sp_U0_ap_done),
    .ap_continue(sp_U0_ap_continue),
    .ap_idle(sp_U0_ap_idle),
    .ap_ready(sp_U0_ap_ready),
    .mem1_V_dout(mem2_V_dout),
    .mem1_V_empty_n(mem2_V_empty_n),
    .mem1_V_read(sp_U0_mem1_V_read),
    .out1_din(sp_U0_out1_din),
    .out1_full_n(f3_full_n),
    .out1_write(sp_U0_out1_write),
    .out2_din(sp_U0_out2_din),
    .out2_full_n(f4_full_n),
    .out2_write(sp_U0_out2_write)
);

top_mac_impl_1 mac_impl_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(mac_impl_1_U0_ap_start),
    .ap_done(mac_impl_1_U0_ap_done),
    .ap_continue(mac_impl_1_U0_ap_continue),
    .ap_idle(mac_impl_1_U0_ap_idle),
    .ap_ready(mac_impl_1_U0_ap_ready),
    .in_1_dout(f1_dout),
    .in_1_empty_n(f1_empty_n),
    .in_1_read(mac_impl_1_U0_in_1_read),
    .in_2_dout(f3_dout),
    .in_2_empty_n(f3_empty_n),
    .in_2_read(mac_impl_1_U0_in_2_read),
    .out_r_din(mac_impl_1_U0_out_r_din),
    .out_r_full_n(f5_full_n),
    .out_r_write(mac_impl_1_U0_out_r_write)
);

top_mac_impl_2 mac_impl_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(mac_impl_2_U0_ap_start),
    .ap_done(mac_impl_2_U0_ap_done),
    .ap_continue(mac_impl_2_U0_ap_continue),
    .ap_idle(mac_impl_2_U0_ap_idle),
    .ap_ready(mac_impl_2_U0_ap_ready),
    .in_1_dout(f2_dout),
    .in_1_empty_n(f2_empty_n),
    .in_1_read(mac_impl_2_U0_in_1_read),
    .in_2_dout(f4_dout),
    .in_2_empty_n(f4_empty_n),
    .in_2_read(mac_impl_2_U0_in_2_read),
    .out_r_din(mac_impl_2_U0_out_r_din),
    .out_r_full_n(f6_full_n),
    .out_r_write(mac_impl_2_U0_out_r_write)
);

top_check check_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(check_U0_ap_start),
    .ap_done(check_U0_ap_done),
    .ap_continue(check_U0_ap_continue),
    .ap_idle(check_U0_ap_idle),
    .ap_ready(check_U0_ap_ready),
    .in1_dout(f5_dout),
    .in1_empty_n(f5_empty_n),
    .in1_read(check_U0_in1_read),
    .in2_dout(f6_dout),
    .in2_empty_n(f6_empty_n),
    .in2_read(check_U0_in2_read),
    .out_V_din(check_U0_out_V_din),
    .out_V_full_n(out_V_full_n),
    .out_V_write(check_U0_out_V_write)
);

top_fifo_w2_d2_S f1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sp3_U0_out1_din),
    .if_full_n(f1_full_n),
    .if_write(sp3_U0_out1_write),
    .if_dout(f1_dout),
    .if_empty_n(f1_empty_n),
    .if_read(mac_impl_1_U0_in_1_read)
);

top_fifo_w2_d2_S f2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sp3_U0_out2_din),
    .if_full_n(f2_full_n),
    .if_write(sp3_U0_out2_write),
    .if_dout(f2_dout),
    .if_empty_n(f2_empty_n),
    .if_read(mac_impl_2_U0_in_1_read)
);

top_fifo_w2_d2_S f3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sp_U0_out1_din),
    .if_full_n(f3_full_n),
    .if_write(sp_U0_out1_write),
    .if_dout(f3_dout),
    .if_empty_n(f3_empty_n),
    .if_read(mac_impl_1_U0_in_2_read)
);

top_fifo_w2_d2_S f4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sp_U0_out2_din),
    .if_full_n(f4_full_n),
    .if_write(sp_U0_out2_write),
    .if_dout(f4_dout),
    .if_empty_n(f4_empty_n),
    .if_read(mac_impl_2_U0_in_2_read)
);

top_fifo_w2_d2_S f5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_impl_1_U0_out_r_din),
    .if_full_n(f5_full_n),
    .if_write(mac_impl_1_U0_out_r_write),
    .if_dout(f5_dout),
    .if_empty_n(f5_empty_n),
    .if_read(check_U0_in1_read)
);

top_fifo_w2_d2_S f6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mac_impl_2_U0_out_r_din),
    .if_full_n(f6_full_n),
    .if_write(mac_impl_2_U0_out_r_write),
    .if_dout(f6_dout),
    .if_empty_n(f6_empty_n),
    .if_read(check_U0_in2_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_check_U0_ap_start <= 1'b0;
    end else begin
        if ((ap_start == 1'b1)) begin
            ap_sync_reg_check_U0_ap_start <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_mac_impl_1_U0_ap_start <= 1'b0;
    end else begin
        if ((ap_start == 1'b1)) begin
            ap_sync_reg_mac_impl_1_U0_ap_start <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_mac_impl_2_U0_ap_start <= 1'b0;
    end else begin
        if ((ap_start == 1'b1)) begin
            ap_sync_reg_mac_impl_2_U0_ap_start <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_sp3_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_sp3_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_sp3_U0_ap_ready <= ap_sync_sp3_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_sp_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_sp_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_sp_U0_ap_ready <= ap_sync_sp_U0_ap_ready;
        end
    end
end

assign ap_done = check_U0_ap_done;

assign ap_idle = (sp_U0_ap_idle & sp3_U0_ap_idle & mac_impl_2_U0_ap_idle & mac_impl_1_U0_ap_idle & check_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_continue = 1'b1;

assign ap_sync_done = check_U0_ap_done;

assign ap_sync_ready = (ap_sync_sp_U0_ap_ready & ap_sync_sp3_U0_ap_ready);

assign ap_sync_sp3_U0_ap_ready = (sp3_U0_ap_ready | ap_sync_reg_sp3_U0_ap_ready);

assign ap_sync_sp_U0_ap_ready = (sp_U0_ap_ready | ap_sync_reg_sp_U0_ap_ready);

assign check_U0_ap_continue = 1'b1;

assign check_U0_ap_start = (ap_sync_reg_check_U0_ap_start | ap_start);

assign mac_impl_1_U0_ap_continue = 1'b1;

assign mac_impl_1_U0_ap_start = (ap_sync_reg_mac_impl_1_U0_ap_start | ap_start);

assign mac_impl_2_U0_ap_continue = 1'b1;

assign mac_impl_2_U0_ap_start = (ap_sync_reg_mac_impl_2_U0_ap_start | ap_start);

assign mem1_V_read = sp3_U0_mem1_V_read;

assign mem2_V_read = sp_U0_mem1_V_read;

assign out_V_din = check_U0_out_V_din;

assign out_V_write = check_U0_out_V_write;

assign sp3_U0_ap_continue = 1'b1;

assign sp3_U0_ap_start = ((ap_sync_reg_sp3_U0_ap_ready ^ 1'b1) & ap_start);

assign sp_U0_ap_continue = 1'b1;

assign sp_U0_ap_start = ((ap_sync_reg_sp_U0_ap_ready ^ 1'b1) & ap_start);

assert property (@(posedge ap_clk) (~out_V_write || out_V_din));
endmodule //top
