// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module vector_add_cmp_4_check_sum (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        out_d_1_dout,
        out_d_1_empty_n,
        out_d_1_read,
        out_d_2_dout,
        out_d_2_empty_n,
        out_d_2_read,
        res_correct_V_din,
        res_correct_V_full_n,
        res_correct_V_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state5 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [3:0] out_d_1_dout;
input   out_d_1_empty_n;
output   out_d_1_read;
input  [3:0] out_d_2_dout;
input   out_d_2_empty_n;
output   out_d_2_read;
output  [0:0] res_correct_V_din;
input   res_correct_V_full_n;
output   res_correct_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg out_d_1_read;
reg out_d_2_read;
reg res_correct_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    out_d_1_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln73_reg_89;
reg    out_d_2_blk_n;
reg    res_correct_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln73_reg_89_pp0_iter1_reg;
reg   [11:0] i_reg_55;
wire   [11:0] i_4_fu_66_p2;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln73_fu_72_p2;
wire   [0:0] icmp_ln870_fu_78_p2;
reg   [0:0] icmp_ln870_reg_93;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_block_pp0_stage0_01001;
wire    ap_CS_fsm_state5;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln73_fu_72_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_55 <= i_4_fu_66_p2;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_55 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln73_reg_89 <= icmp_ln73_fu_72_p2;
        icmp_ln73_reg_89_pp0_iter1_reg <= icmp_ln73_reg_89;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln73_reg_89 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln870_reg_93 <= icmp_ln870_fu_78_p2;
    end
end

always @ (*) begin
    if ((icmp_ln73_fu_72_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln73_reg_89 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_d_1_blk_n = out_d_1_empty_n;
    end else begin
        out_d_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln73_reg_89 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_d_1_read = 1'b1;
    end else begin
        out_d_1_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln73_reg_89 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_d_2_blk_n = out_d_2_empty_n;
    end else begin
        out_d_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln73_reg_89 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_d_2_read = 1'b1;
    end else begin
        out_d_2_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln73_reg_89_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        res_correct_V_blk_n = res_correct_V_full_n;
    end else begin
        res_correct_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln73_reg_89_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        res_correct_V_write = 1'b1;
    end else begin
        res_correct_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln73_fu_72_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)) & ~((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)) | ((icmp_ln73_fu_72_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((icmp_ln73_reg_89_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (res_correct_V_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln73_reg_89 == 1'd0) & (out_d_2_empty_n == 1'b0)) | ((icmp_ln73_reg_89 == 1'd0) & (out_d_1_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((icmp_ln73_reg_89_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (res_correct_V_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln73_reg_89 == 1'd0) & (out_d_2_empty_n == 1'b0)) | ((icmp_ln73_reg_89 == 1'd0) & (out_d_1_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((icmp_ln73_reg_89_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (res_correct_V_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln73_reg_89 == 1'd0) & (out_d_2_empty_n == 1'b0)) | ((icmp_ln73_reg_89 == 1'd0) & (out_d_1_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((icmp_ln73_reg_89 == 1'd0) & (out_d_2_empty_n == 1'b0)) | ((icmp_ln73_reg_89 == 1'd0) & (out_d_1_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = ((icmp_ln73_reg_89_pp0_iter1_reg == 1'd0) & (res_correct_V_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign i_4_fu_66_p2 = (i_reg_55 + 12'd1);

assign icmp_ln73_fu_72_p2 = ((i_reg_55 == 12'd2048) ? 1'b1 : 1'b0);

assign icmp_ln870_fu_78_p2 = ((out_d_1_dout == out_d_2_dout) ? 1'b1 : 1'b0);

assign res_correct_V_din = icmp_ln870_reg_93;

endmodule //vector_add_cmp_4_check_sum
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps

module vector_add_cmp_4_fifo_w4_d2_S_shiftReg (
    clk,
    data,
    ce,
    a,
    q);

parameter DATA_WIDTH = 32'd4;
parameter ADDR_WIDTH = 32'd1;
parameter DEPTH = 2'd2;

input clk;
input [DATA_WIDTH-1:0] data;
input ce;
input [ADDR_WIDTH-1:0] a;
output [DATA_WIDTH-1:0] q;

reg[DATA_WIDTH-1:0] SRL_SIG [0:DEPTH-1];
integer i;

always @ (posedge clk)
    begin
        if (ce)
        begin
            for (i=0;i<DEPTH-1;i=i+1)
                SRL_SIG[i+1] <= SRL_SIG[i];
            SRL_SIG[0] <= data;
        end
    end

assign q = SRL_SIG[a];

endmodule

module vector_add_cmp_4_fifo_w4_d2_S (
    clk,
    reset,
    if_empty_n,
    if_read_ce,
    if_read,
    if_dout,
    if_full_n,
    if_write_ce,
    if_write,
    if_din);

parameter MEM_STYLE   = "shiftreg";
parameter DATA_WIDTH  = 32'd4;
parameter ADDR_WIDTH  = 32'd1;
parameter DEPTH       = 2'd2;

input clk;
input reset;
output if_empty_n;
input if_read_ce;
input if_read;
output[DATA_WIDTH - 1:0] if_dout;
output if_full_n;
input if_write_ce;
input if_write;
input[DATA_WIDTH - 1:0] if_din;

wire[ADDR_WIDTH - 1:0] shiftReg_addr ;
wire[DATA_WIDTH - 1:0] shiftReg_data, shiftReg_q;
wire                     shiftReg_ce;
reg[ADDR_WIDTH:0] mOutPtr = ~{(ADDR_WIDTH+1){1'b0}};
reg internal_empty_n = 0;
reg internal_full_n = 1;

assign if_full_n = internal_full_n;
assign if_empty_n = internal_empty_n;
assign shiftReg_data = if_din;
assign if_dout = shiftReg_q;

always @ (posedge clk) begin
    if (reset == 1'b1)
    begin
        mOutPtr <= ~{ADDR_WIDTH+1{1'b0}};
        internal_empty_n <= 1'b0;
        internal_full_n <= 1'b1;
    end
    else begin
        if (((if_read & if_read_ce) == 1 & internal_empty_n == 1) && 
            ((if_write & if_write_ce) == 0 | internal_full_n == 0))
        begin
            mOutPtr <= mOutPtr - 2'd1;
            if (mOutPtr == 2'd0)
                internal_empty_n <= 1'b0;
            internal_full_n <= 1'b1;
        end 
        else if (((if_read & if_read_ce) == 0 | internal_empty_n == 0) && 
            ((if_write & if_write_ce) == 1 & internal_full_n == 1))
        begin
            mOutPtr <= mOutPtr + 2'd1;
            internal_empty_n <= 1'b1;
            if (mOutPtr == DEPTH - 2'd2)
                internal_full_n <= 1'b0;
        end 
    end
end

assign shiftReg_addr = mOutPtr[ADDR_WIDTH] == 1'b0 ? mOutPtr[ADDR_WIDTH-1:0]:{ADDR_WIDTH{1'b0}};
assign shiftReg_ce = (if_write & if_write_ce) & internal_full_n;

vector_add_cmp_4_fifo_w4_d2_S_shiftReg 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH),
    .DEPTH(DEPTH))
U_vector_add_cmp_4_fifo_w4_d2_S_ram (
    .clk(clk),
    .data(shiftReg_data),
    .ce(shiftReg_ce),
    .a(shiftReg_addr),
    .q(shiftReg_q));

endmodule  

// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module vector_add_cmp_4_sp_data (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_a_V_dout,
        in_a_V_empty_n,
        in_a_V_read,
        in_b_V_dout,
        in_b_V_empty_n,
        in_b_V_read,
        in_c_V_dout,
        in_c_V_empty_n,
        in_c_V_read,
        in_a_1_din,
        in_a_1_full_n,
        in_a_1_write,
        in_b_1_din,
        in_b_1_full_n,
        in_b_1_write,
        in_c_1_din,
        in_c_1_full_n,
        in_c_1_write,
        in_a_2_din,
        in_a_2_full_n,
        in_a_2_write,
        in_b_2_din,
        in_b_2_full_n,
        in_b_2_write,
        in_c_2_din,
        in_c_2_full_n,
        in_c_2_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [3:0] in_a_V_dout;
input   in_a_V_empty_n;
output   in_a_V_read;
input  [3:0] in_b_V_dout;
input   in_b_V_empty_n;
output   in_b_V_read;
input  [3:0] in_c_V_dout;
input   in_c_V_empty_n;
output   in_c_V_read;
output  [3:0] in_a_1_din;
input   in_a_1_full_n;
output   in_a_1_write;
output  [3:0] in_b_1_din;
input   in_b_1_full_n;
output   in_b_1_write;
output  [3:0] in_c_1_din;
input   in_c_1_full_n;
output   in_c_1_write;
output  [3:0] in_a_2_din;
input   in_a_2_full_n;
output   in_a_2_write;
output  [3:0] in_b_2_din;
input   in_b_2_full_n;
output   in_b_2_write;
output  [3:0] in_c_2_din;
input   in_c_2_full_n;
output   in_c_2_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_a_V_read;
reg in_b_V_read;
reg in_c_V_read;
reg in_a_1_write;
reg in_b_1_write;
reg in_c_1_write;
reg in_a_2_write;
reg in_b_2_write;
reg in_c_2_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in_a_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln51_reg_142;
reg    in_b_V_blk_n;
reg    in_c_V_blk_n;
reg    in_a_1_blk_n;
reg    in_b_1_blk_n;
reg    in_c_1_blk_n;
reg    in_a_2_blk_n;
reg    in_b_2_blk_n;
reg    in_c_2_blk_n;
reg   [11:0] i_reg_114;
wire   [11:0] i_3_fu_125_p2;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln51_fu_131_p2;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_block_pp0_stage0_01001;
wire    ap_CS_fsm_state4;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln51_fu_131_p2 == 1'd0))) begin
        i_reg_114 <= i_3_fu_125_p2;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_114 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln51_reg_142 <= icmp_ln51_fu_131_p2;
    end
end

always @ (*) begin
    if ((icmp_ln51_fu_131_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_142 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_1_blk_n = in_a_1_full_n;
    end else begin
        in_a_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_142 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_1_write = 1'b1;
    end else begin
        in_a_1_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_142 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_2_blk_n = in_a_2_full_n;
    end else begin
        in_a_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_142 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_2_write = 1'b1;
    end else begin
        in_a_2_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_142 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_V_blk_n = in_a_V_empty_n;
    end else begin
        in_a_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_142 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_V_read = 1'b1;
    end else begin
        in_a_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_142 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_b_1_blk_n = in_b_1_full_n;
    end else begin
        in_b_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_142 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_b_1_write = 1'b1;
    end else begin
        in_b_1_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_142 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_b_2_blk_n = in_b_2_full_n;
    end else begin
        in_b_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_142 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_b_2_write = 1'b1;
    end else begin
        in_b_2_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_142 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_b_V_blk_n = in_b_V_empty_n;
    end else begin
        in_b_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_142 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_b_V_read = 1'b1;
    end else begin
        in_b_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_142 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_c_1_blk_n = in_c_1_full_n;
    end else begin
        in_c_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_142 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_c_1_write = 1'b1;
    end else begin
        in_c_1_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_142 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_c_2_blk_n = in_c_2_full_n;
    end else begin
        in_c_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_142 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_c_2_write = 1'b1;
    end else begin
        in_c_2_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_142 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_c_V_blk_n = in_c_V_empty_n;
    end else begin
        in_c_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_142 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_c_V_read = 1'b1;
    end else begin
        in_c_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln51_fu_131_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln51_fu_131_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln51_reg_142 == 1'd0) & (in_a_1_full_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_a_V_empty_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_c_2_full_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_c_1_full_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_c_V_empty_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_b_2_full_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_b_1_full_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_b_V_empty_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_a_2_full_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln51_reg_142 == 1'd0) & (in_a_1_full_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_a_V_empty_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_c_2_full_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_c_1_full_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_c_V_empty_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_b_2_full_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_b_1_full_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_b_V_empty_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_a_2_full_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln51_reg_142 == 1'd0) & (in_a_1_full_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_a_V_empty_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_c_2_full_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_c_1_full_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_c_V_empty_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_b_2_full_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_b_1_full_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_b_V_empty_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_a_2_full_n == 1'b0))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((icmp_ln51_reg_142 == 1'd0) & (in_a_1_full_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_a_V_empty_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_c_2_full_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_c_1_full_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_c_V_empty_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_b_2_full_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_b_1_full_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_b_V_empty_n == 1'b0)) | ((icmp_ln51_reg_142 == 1'd0) & (in_a_2_full_n == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign i_3_fu_125_p2 = (i_reg_114 + 12'd1);

assign icmp_ln51_fu_131_p2 = ((i_reg_114 == 12'd2048) ? 1'b1 : 1'b0);

assign in_a_1_din = in_a_V_dout;

assign in_a_2_din = in_a_V_dout;

assign in_b_1_din = in_b_V_dout;

assign in_b_2_din = in_b_V_dout;

assign in_c_1_din = in_c_V_dout;

assign in_c_2_din = in_c_V_dout;

endmodule //vector_add_cmp_4_sp_data
// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="vector_add_cmp_4_vector_add_cmp_4,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.111000,HLS_SYN_LAT=2055,HLS_SYN_TPT=2052,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=898,HLS_SYN_LUT=1126,HLS_VERSION=2020_2}" *)

module vector_add_cmp_4 (
        in_a_V_dout,
        in_a_V_empty_n,
        in_a_V_read,
        in_b_V_dout,
        in_b_V_empty_n,
        in_b_V_read,
        in_c_V_dout,
        in_c_V_empty_n,
        in_c_V_read,
        res_correct_V_din,
        res_correct_V_full_n,
        res_correct_V_write,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);


input  [3:0] in_a_V_dout;
input   in_a_V_empty_n;
output   in_a_V_read;
input  [3:0] in_b_V_dout;
input   in_b_V_empty_n;
output   in_b_V_read;
input  [3:0] in_c_V_dout;
input   in_c_V_empty_n;
output   in_c_V_read;
output  [0:0] res_correct_V_din;
input   res_correct_V_full_n;
output   res_correct_V_write;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire    sp_data_U0_ap_start;
wire    sp_data_U0_ap_done;
wire    sp_data_U0_ap_continue;
wire    sp_data_U0_ap_idle;
wire    sp_data_U0_ap_ready;
wire    sp_data_U0_in_a_V_read;
wire    sp_data_U0_in_b_V_read;
wire    sp_data_U0_in_c_V_read;
wire   [3:0] sp_data_U0_in_a_1_din;
wire    sp_data_U0_in_a_1_write;
wire   [3:0] sp_data_U0_in_b_1_din;
wire    sp_data_U0_in_b_1_write;
wire   [3:0] sp_data_U0_in_c_1_din;
wire    sp_data_U0_in_c_1_write;
wire   [3:0] sp_data_U0_in_a_2_din;
wire    sp_data_U0_in_a_2_write;
wire   [3:0] sp_data_U0_in_b_2_din;
wire    sp_data_U0_in_b_2_write;
wire   [3:0] sp_data_U0_in_c_2_din;
wire    sp_data_U0_in_c_2_write;
wire    vector_add_impl_1_U0_ap_start;
wire    vector_add_impl_1_U0_ap_done;
wire    vector_add_impl_1_U0_ap_continue;
wire    vector_add_impl_1_U0_ap_idle;
wire    vector_add_impl_1_U0_ap_ready;
wire    vector_add_impl_1_U0_in_a_read;
wire    vector_add_impl_1_U0_in_b_read;
wire    vector_add_impl_1_U0_in_c_read;
wire   [3:0] vector_add_impl_1_U0_out_d_din;
wire    vector_add_impl_1_U0_out_d_write;
reg    ap_sync_reg_vector_add_impl_1_U0_ap_start;
wire    vector_add_impl_2_U0_ap_start;
wire    vector_add_impl_2_U0_ap_done;
wire    vector_add_impl_2_U0_ap_continue;
wire    vector_add_impl_2_U0_ap_idle;
wire    vector_add_impl_2_U0_ap_ready;
wire    vector_add_impl_2_U0_in_a_read;
wire    vector_add_impl_2_U0_in_b_read;
wire    vector_add_impl_2_U0_in_c_read;
wire   [3:0] vector_add_impl_2_U0_out_d_din;
wire    vector_add_impl_2_U0_out_d_write;
reg    ap_sync_reg_vector_add_impl_2_U0_ap_start;
wire    check_sum_U0_ap_start;
wire    check_sum_U0_ap_done;
wire    check_sum_U0_ap_continue;
wire    check_sum_U0_ap_idle;
wire    check_sum_U0_ap_ready;
wire    check_sum_U0_out_d_1_read;
wire    check_sum_U0_out_d_2_read;
wire   [0:0] check_sum_U0_res_correct_V_din;
wire    check_sum_U0_res_correct_V_write;
reg    ap_sync_reg_check_sum_U0_ap_start;
wire    ap_sync_continue;
wire    in_a_1_full_n;
wire   [3:0] in_a_1_dout;
wire    in_a_1_empty_n;
wire    in_b_1_full_n;
wire   [3:0] in_b_1_dout;
wire    in_b_1_empty_n;
wire    in_c_1_full_n;
wire   [3:0] in_c_1_dout;
wire    in_c_1_empty_n;
wire    in_a_2_full_n;
wire   [3:0] in_a_2_dout;
wire    in_a_2_empty_n;
wire    in_b_2_full_n;
wire   [3:0] in_b_2_dout;
wire    in_b_2_empty_n;
wire    in_c_2_full_n;
wire   [3:0] in_c_2_dout;
wire    in_c_2_empty_n;
wire    out_d_1_full_n;
wire   [3:0] out_d_1_dout;
wire    out_d_1_empty_n;
wire    out_d_2_full_n;
wire   [3:0] out_d_2_dout;
wire    out_d_2_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_vector_add_impl_1_U0_ap_start = 1'b0;
#0 ap_sync_reg_vector_add_impl_2_U0_ap_start = 1'b0;
#0 ap_sync_reg_check_sum_U0_ap_start = 1'b0;
end

vector_add_cmp_4_sp_data sp_data_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(sp_data_U0_ap_start),
    .ap_done(sp_data_U0_ap_done),
    .ap_continue(sp_data_U0_ap_continue),
    .ap_idle(sp_data_U0_ap_idle),
    .ap_ready(sp_data_U0_ap_ready),
    .in_a_V_dout(in_a_V_dout),
    .in_a_V_empty_n(in_a_V_empty_n),
    .in_a_V_read(sp_data_U0_in_a_V_read),
    .in_b_V_dout(in_b_V_dout),
    .in_b_V_empty_n(in_b_V_empty_n),
    .in_b_V_read(sp_data_U0_in_b_V_read),
    .in_c_V_dout(in_c_V_dout),
    .in_c_V_empty_n(in_c_V_empty_n),
    .in_c_V_read(sp_data_U0_in_c_V_read),
    .in_a_1_din(sp_data_U0_in_a_1_din),
    .in_a_1_full_n(in_a_1_full_n),
    .in_a_1_write(sp_data_U0_in_a_1_write),
    .in_b_1_din(sp_data_U0_in_b_1_din),
    .in_b_1_full_n(in_b_1_full_n),
    .in_b_1_write(sp_data_U0_in_b_1_write),
    .in_c_1_din(sp_data_U0_in_c_1_din),
    .in_c_1_full_n(in_c_1_full_n),
    .in_c_1_write(sp_data_U0_in_c_1_write),
    .in_a_2_din(sp_data_U0_in_a_2_din),
    .in_a_2_full_n(in_a_2_full_n),
    .in_a_2_write(sp_data_U0_in_a_2_write),
    .in_b_2_din(sp_data_U0_in_b_2_din),
    .in_b_2_full_n(in_b_2_full_n),
    .in_b_2_write(sp_data_U0_in_b_2_write),
    .in_c_2_din(sp_data_U0_in_c_2_din),
    .in_c_2_full_n(in_c_2_full_n),
    .in_c_2_write(sp_data_U0_in_c_2_write)
);

vector_add_cmp_4_vector_add_impl_1 vector_add_impl_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(vector_add_impl_1_U0_ap_start),
    .ap_done(vector_add_impl_1_U0_ap_done),
    .ap_continue(vector_add_impl_1_U0_ap_continue),
    .ap_idle(vector_add_impl_1_U0_ap_idle),
    .ap_ready(vector_add_impl_1_U0_ap_ready),
    .in_a_dout(in_a_1_dout),
    .in_a_empty_n(in_a_1_empty_n),
    .in_a_read(vector_add_impl_1_U0_in_a_read),
    .in_b_dout(in_b_1_dout),
    .in_b_empty_n(in_b_1_empty_n),
    .in_b_read(vector_add_impl_1_U0_in_b_read),
    .in_c_dout(in_c_1_dout),
    .in_c_empty_n(in_c_1_empty_n),
    .in_c_read(vector_add_impl_1_U0_in_c_read),
    .out_d_din(vector_add_impl_1_U0_out_d_din),
    .out_d_full_n(out_d_1_full_n),
    .out_d_write(vector_add_impl_1_U0_out_d_write)
);

vector_add_cmp_4_vector_add_impl_2 vector_add_impl_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(vector_add_impl_2_U0_ap_start),
    .ap_done(vector_add_impl_2_U0_ap_done),
    .ap_continue(vector_add_impl_2_U0_ap_continue),
    .ap_idle(vector_add_impl_2_U0_ap_idle),
    .ap_ready(vector_add_impl_2_U0_ap_ready),
    .in_a_dout(in_a_2_dout),
    .in_a_empty_n(in_a_2_empty_n),
    .in_a_read(vector_add_impl_2_U0_in_a_read),
    .in_b_dout(in_b_2_dout),
    .in_b_empty_n(in_b_2_empty_n),
    .in_b_read(vector_add_impl_2_U0_in_b_read),
    .in_c_dout(in_c_2_dout),
    .in_c_empty_n(in_c_2_empty_n),
    .in_c_read(vector_add_impl_2_U0_in_c_read),
    .out_d_din(vector_add_impl_2_U0_out_d_din),
    .out_d_full_n(out_d_2_full_n),
    .out_d_write(vector_add_impl_2_U0_out_d_write)
);

vector_add_cmp_4_check_sum check_sum_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(check_sum_U0_ap_start),
    .ap_done(check_sum_U0_ap_done),
    .ap_continue(check_sum_U0_ap_continue),
    .ap_idle(check_sum_U0_ap_idle),
    .ap_ready(check_sum_U0_ap_ready),
    .out_d_1_dout(out_d_1_dout),
    .out_d_1_empty_n(out_d_1_empty_n),
    .out_d_1_read(check_sum_U0_out_d_1_read),
    .out_d_2_dout(out_d_2_dout),
    .out_d_2_empty_n(out_d_2_empty_n),
    .out_d_2_read(check_sum_U0_out_d_2_read),
    .res_correct_V_din(check_sum_U0_res_correct_V_din),
    .res_correct_V_full_n(res_correct_V_full_n),
    .res_correct_V_write(check_sum_U0_res_correct_V_write)
);

vector_add_cmp_4_fifo_w4_d2_S in_a_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sp_data_U0_in_a_1_din),
    .if_full_n(in_a_1_full_n),
    .if_write(sp_data_U0_in_a_1_write),
    .if_dout(in_a_1_dout),
    .if_empty_n(in_a_1_empty_n),
    .if_read(vector_add_impl_1_U0_in_a_read)
);

vector_add_cmp_4_fifo_w4_d2_S in_b_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sp_data_U0_in_b_1_din),
    .if_full_n(in_b_1_full_n),
    .if_write(sp_data_U0_in_b_1_write),
    .if_dout(in_b_1_dout),
    .if_empty_n(in_b_1_empty_n),
    .if_read(vector_add_impl_1_U0_in_b_read)
);

vector_add_cmp_4_fifo_w4_d2_S in_c_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sp_data_U0_in_c_1_din),
    .if_full_n(in_c_1_full_n),
    .if_write(sp_data_U0_in_c_1_write),
    .if_dout(in_c_1_dout),
    .if_empty_n(in_c_1_empty_n),
    .if_read(vector_add_impl_1_U0_in_c_read)
);

vector_add_cmp_4_fifo_w4_d2_S in_a_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sp_data_U0_in_a_2_din),
    .if_full_n(in_a_2_full_n),
    .if_write(sp_data_U0_in_a_2_write),
    .if_dout(in_a_2_dout),
    .if_empty_n(in_a_2_empty_n),
    .if_read(vector_add_impl_2_U0_in_a_read)
);

vector_add_cmp_4_fifo_w4_d2_S in_b_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sp_data_U0_in_b_2_din),
    .if_full_n(in_b_2_full_n),
    .if_write(sp_data_U0_in_b_2_write),
    .if_dout(in_b_2_dout),
    .if_empty_n(in_b_2_empty_n),
    .if_read(vector_add_impl_2_U0_in_b_read)
);

vector_add_cmp_4_fifo_w4_d2_S in_c_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sp_data_U0_in_c_2_din),
    .if_full_n(in_c_2_full_n),
    .if_write(sp_data_U0_in_c_2_write),
    .if_dout(in_c_2_dout),
    .if_empty_n(in_c_2_empty_n),
    .if_read(vector_add_impl_2_U0_in_c_read)
);

vector_add_cmp_4_fifo_w4_d2_S out_d_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(vector_add_impl_1_U0_out_d_din),
    .if_full_n(out_d_1_full_n),
    .if_write(vector_add_impl_1_U0_out_d_write),
    .if_dout(out_d_1_dout),
    .if_empty_n(out_d_1_empty_n),
    .if_read(check_sum_U0_out_d_1_read)
);

vector_add_cmp_4_fifo_w4_d2_S out_d_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(vector_add_impl_2_U0_out_d_din),
    .if_full_n(out_d_2_full_n),
    .if_write(vector_add_impl_2_U0_out_d_write),
    .if_dout(out_d_2_dout),
    .if_empty_n(out_d_2_empty_n),
    .if_read(check_sum_U0_out_d_2_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_check_sum_U0_ap_start <= 1'b0;
    end else begin
        if ((ap_start == 1'b1)) begin
            ap_sync_reg_check_sum_U0_ap_start <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_vector_add_impl_1_U0_ap_start <= 1'b0;
    end else begin
        if ((ap_start == 1'b1)) begin
            ap_sync_reg_vector_add_impl_1_U0_ap_start <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_vector_add_impl_2_U0_ap_start <= 1'b0;
    end else begin
        if ((ap_start == 1'b1)) begin
            ap_sync_reg_vector_add_impl_2_U0_ap_start <= 1'b1;
        end
    end
end

assign ap_done = check_sum_U0_ap_done;

assign ap_idle = (vector_add_impl_2_U0_ap_idle & vector_add_impl_1_U0_ap_idle & sp_data_U0_ap_idle & check_sum_U0_ap_idle);

assign ap_ready = sp_data_U0_ap_ready;

assign ap_sync_continue = 1'b1;

assign ap_sync_done = check_sum_U0_ap_done;

assign ap_sync_ready = sp_data_U0_ap_ready;

assign check_sum_U0_ap_continue = 1'b1;

assign check_sum_U0_ap_start = (ap_sync_reg_check_sum_U0_ap_start | ap_start);

assign in_a_V_read = sp_data_U0_in_a_V_read;

assign in_b_V_read = sp_data_U0_in_b_V_read;

assign in_c_V_read = sp_data_U0_in_c_V_read;

assign res_correct_V_din = check_sum_U0_res_correct_V_din;

assign res_correct_V_write = check_sum_U0_res_correct_V_write;

assign sp_data_U0_ap_continue = 1'b1;

assign sp_data_U0_ap_start = ap_start;

assign vector_add_impl_1_U0_ap_continue = 1'b1;

assign vector_add_impl_1_U0_ap_start = (ap_sync_reg_vector_add_impl_1_U0_ap_start | ap_start);

assign vector_add_impl_2_U0_ap_continue = 1'b1;

assign vector_add_impl_2_U0_ap_start = (ap_sync_reg_vector_add_impl_2_U0_ap_start | ap_start);

assert property (@(posedge ap_clk) (~res_correct_V_write || res_correct_V_din));

endmodule //vector_add_cmp_4
// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module vector_add_cmp_4_vector_add_impl_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_a_dout,
        in_a_empty_n,
        in_a_read,
        in_b_dout,
        in_b_empty_n,
        in_b_read,
        in_c_dout,
        in_c_empty_n,
        in_c_read,
        out_d_din,
        out_d_full_n,
        out_d_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state5 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [3:0] in_a_dout;
input   in_a_empty_n;
output   in_a_read;
input  [3:0] in_b_dout;
input   in_b_empty_n;
output   in_b_read;
input  [3:0] in_c_dout;
input   in_c_empty_n;
output   in_c_read;
output  [3:0] out_d_din;
input   out_d_full_n;
output   out_d_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_a_read;
reg in_b_read;
reg in_c_read;
reg out_d_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in_a_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln13_reg_103;
reg    in_b_blk_n;
reg    in_c_blk_n;
reg    out_d_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln13_reg_103_pp0_iter1_reg;
reg   [11:0] i_reg_63;
wire   [11:0] i_2_fu_74_p2;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln13_fu_80_p2;
wire   [3:0] add_ln162_1_fu_92_p2;
reg   [3:0] add_ln162_1_reg_107;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_block_pp0_stage0_01001;
wire   [3:0] add_ln162_fu_86_p2;
wire    ap_CS_fsm_state5;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln13_fu_80_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_63 <= i_2_fu_74_p2;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_63 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln13_reg_103 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln162_1_reg_107 <= add_ln162_1_fu_92_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln13_reg_103 <= icmp_ln13_fu_80_p2;
        icmp_ln13_reg_103_pp0_iter1_reg <= icmp_ln13_reg_103;
    end
end

always @ (*) begin
    if ((icmp_ln13_fu_80_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_103 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_blk_n = in_a_empty_n;
    end else begin
        in_a_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_103 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_read = 1'b1;
    end else begin
        in_a_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_103 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_b_blk_n = in_b_empty_n;
    end else begin
        in_b_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_103 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_b_read = 1'b1;
    end else begin
        in_b_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_103 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_c_blk_n = in_c_empty_n;
    end else begin
        in_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_103 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_c_read = 1'b1;
    end else begin
        in_c_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_103_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        out_d_blk_n = out_d_full_n;
    end else begin
        out_d_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_103_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        out_d_write = 1'b1;
    end else begin
        out_d_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln13_fu_80_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)) & ~((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)) | ((icmp_ln13_fu_80_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln162_1_fu_92_p2 = (add_ln162_fu_86_p2 + in_b_dout);

assign add_ln162_fu_86_p2 = (in_a_dout + in_c_dout);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((icmp_ln13_reg_103_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (out_d_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln13_reg_103 == 1'd0) & (in_c_empty_n == 1'b0)) | ((icmp_ln13_reg_103 == 1'd0) & (in_b_empty_n == 1'b0)) | ((icmp_ln13_reg_103 == 1'd0) & (in_a_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((icmp_ln13_reg_103_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (out_d_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln13_reg_103 == 1'd0) & (in_c_empty_n == 1'b0)) | ((icmp_ln13_reg_103 == 1'd0) & (in_b_empty_n == 1'b0)) | ((icmp_ln13_reg_103 == 1'd0) & (in_a_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((icmp_ln13_reg_103_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (out_d_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln13_reg_103 == 1'd0) & (in_c_empty_n == 1'b0)) | ((icmp_ln13_reg_103 == 1'd0) & (in_b_empty_n == 1'b0)) | ((icmp_ln13_reg_103 == 1'd0) & (in_a_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((icmp_ln13_reg_103 == 1'd0) & (in_c_empty_n == 1'b0)) | ((icmp_ln13_reg_103 == 1'd0) & (in_b_empty_n == 1'b0)) | ((icmp_ln13_reg_103 == 1'd0) & (in_a_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = ((icmp_ln13_reg_103_pp0_iter1_reg == 1'd0) & (out_d_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign i_2_fu_74_p2 = (i_reg_63 + 12'd1);

assign icmp_ln13_fu_80_p2 = ((i_reg_63 == 12'd2048) ? 1'b1 : 1'b0);

assign out_d_din = add_ln162_1_reg_107;

endmodule //vector_add_cmp_4_vector_add_impl_1
// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module vector_add_cmp_4_vector_add_impl_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_a_dout,
        in_a_empty_n,
        in_a_read,
        in_b_dout,
        in_b_empty_n,
        in_b_read,
        in_c_dout,
        in_c_empty_n,
        in_c_read,
        out_d_din,
        out_d_full_n,
        out_d_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_pp0_stage0 = 4'd2;
parameter    ap_ST_fsm_pp0_stage1 = 4'd4;
parameter    ap_ST_fsm_state6 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [3:0] in_a_dout;
input   in_a_empty_n;
output   in_a_read;
input  [3:0] in_b_dout;
input   in_b_empty_n;
output   in_b_read;
input  [3:0] in_c_dout;
input   in_c_empty_n;
output   in_c_read;
output  [3:0] out_d_din;
input   out_d_full_n;
output   out_d_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_a_read;
reg in_b_read;
reg in_c_read;
reg out_d_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in_a_blk_n;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage1;
reg   [0:0] tmp_reg_108;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg    in_b_blk_n;
reg    in_c_blk_n;
reg    out_d_blk_n;
reg   [0:0] tmp_reg_108_pp0_iter1_reg;
reg   [11:0] i_reg_65;
wire   [3:0] grp_fu_83_p2;
reg   [3:0] reg_89;
reg    ap_block_state3_pp0_stage1_iter0;
reg    ap_block_state5_pp0_stage1_iter1;
reg    ap_block_pp0_stage1_11001;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state4_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] tmp_fu_94_p3;
wire   [11:0] i_1_fu_102_p2;
reg   [11:0] i_1_reg_112;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_block_pp0_stage1_subdone;
reg   [11:0] ap_phi_mux_i_phi_fu_69_p4;
reg    ap_block_pp0_stage0_01001;
reg    ap_block_pp0_stage1_01001;
wire   [3:0] grp_fu_77_p2;
wire    ap_CS_fsm_state6;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_reg_108 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_65 <= i_1_reg_112;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_65 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_108 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        i_1_reg_112 <= i_1_fu_102_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_reg_108 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_reg_108 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_89 <= grp_fu_83_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_reg_108 <= ap_phi_mux_i_phi_fu_69_p4[32'd11];
        tmp_reg_108_pp0_iter1_reg <= tmp_reg_108;
    end
end

always @ (*) begin
    if ((tmp_fu_94_p3 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_reg_108 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_i_phi_fu_69_p4 = i_1_reg_112;
    end else begin
        ap_phi_mux_i_phi_fu_69_p4 = i_reg_65;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_reg_108 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_reg_108 == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        in_a_blk_n = in_a_empty_n;
    end else begin
        in_a_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_reg_108 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_reg_108 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        in_a_read = 1'b1;
    end else begin
        in_a_read = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_reg_108 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_reg_108 == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        in_b_blk_n = in_b_empty_n;
    end else begin
        in_b_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_reg_108 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_reg_108 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        in_b_read = 1'b1;
    end else begin
        in_b_read = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_reg_108 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_reg_108 == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        in_c_blk_n = in_c_empty_n;
    end else begin
        in_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_reg_108 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_reg_108 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        in_c_read = 1'b1;
    end else begin
        in_c_read = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_reg_108_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_reg_108 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_d_blk_n = out_d_full_n;
    end else begin
        out_d_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((tmp_reg_108_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_reg_108 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_d_write = 1'b1;
    end else begin
        out_d_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (tmp_fu_94_p3 == 1'd1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (tmp_fu_94_p3 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage1)) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((tmp_reg_108 == 1'd0) & (out_d_full_n == 1'b0)) | ((tmp_reg_108 == 1'd0) & (in_c_empty_n == 1'b0)) | ((tmp_reg_108 == 1'd0) & (in_b_empty_n == 1'b0)) | ((tmp_reg_108 == 1'd0) & (in_a_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((tmp_reg_108 == 1'd0) & (out_d_full_n == 1'b0)) | ((tmp_reg_108 == 1'd0) & (in_c_empty_n == 1'b0)) | ((tmp_reg_108 == 1'd0) & (in_b_empty_n == 1'b0)) | ((tmp_reg_108 == 1'd0) & (in_a_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((tmp_reg_108 == 1'd0) & (out_d_full_n == 1'b0)) | ((tmp_reg_108 == 1'd0) & (in_c_empty_n == 1'b0)) | ((tmp_reg_108 == 1'd0) & (in_b_empty_n == 1'b0)) | ((tmp_reg_108 == 1'd0) & (in_a_empty_n == 1'b0))));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = (((tmp_reg_108_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (out_d_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((tmp_reg_108 == 1'd0) & (in_c_empty_n == 1'b0)) | ((tmp_reg_108 == 1'd0) & (in_b_empty_n == 1'b0)) | ((tmp_reg_108 == 1'd0) & (in_a_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((tmp_reg_108_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (out_d_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((tmp_reg_108 == 1'd0) & (in_c_empty_n == 1'b0)) | ((tmp_reg_108 == 1'd0) & (in_b_empty_n == 1'b0)) | ((tmp_reg_108 == 1'd0) & (in_a_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((tmp_reg_108_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (out_d_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((tmp_reg_108 == 1'd0) & (in_c_empty_n == 1'b0)) | ((tmp_reg_108 == 1'd0) & (in_b_empty_n == 1'b0)) | ((tmp_reg_108 == 1'd0) & (in_a_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage1_iter0 = (((tmp_reg_108 == 1'd0) & (in_c_empty_n == 1'b0)) | ((tmp_reg_108 == 1'd0) & (in_b_empty_n == 1'b0)) | ((tmp_reg_108 == 1'd0) & (in_a_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = (((tmp_reg_108 == 1'd0) & (out_d_full_n == 1'b0)) | ((tmp_reg_108 == 1'd0) & (in_c_empty_n == 1'b0)) | ((tmp_reg_108 == 1'd0) & (in_b_empty_n == 1'b0)) | ((tmp_reg_108 == 1'd0) & (in_a_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state5_pp0_stage1_iter1 = ((tmp_reg_108_pp0_iter1_reg == 1'd0) & (out_d_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign grp_fu_77_p2 = (in_a_dout + in_c_dout);

assign grp_fu_83_p2 = (grp_fu_77_p2 + in_b_dout);

assign i_1_fu_102_p2 = (i_reg_65 + 12'd2);

assign out_d_din = reg_89;

assign tmp_fu_94_p3 = ap_phi_mux_i_phi_fu_69_p4[32'd11];

endmodule //vector_add_cmp_4_vector_add_impl_2
